### ISSUE TITLE
Self argument missing

### ISSUE THREAD

**Issue by pn** [Maydmor/pydantic-computed#5]
Hello,
Thank you for this useful library. I've got following issue:

When using this library I get error from mypy:
> error: Self argument missing for a non-static method (or an invalid type for self)

When I add `self` to calculated method the library rises
> KeyError: 'self'

Maybe the library should handle `self` argument?

Also why not access values from the class through `self` instead of declaring them again in method attributes (it would avoid declaring same types again and would help linters find bugs)?

**Comment by Maydmor** [comment]
Thank you for the Feedback :)
Internally the computation is triggered by using pydantics validators, which are class methods. So, by Design, the Computed Method can not reference the instance by self.
